### ISSUE TITLE
New features

### ISSUE THREAD

**Issue by Re04nan** [raquel-maia/nordeste-geek#1]
Olá @raquel-maia!
Não sou nenhum _expert_ em _frontend_ ou até mesmo _UX Design_ ou _UI_, mas posso sugerir adicionar, por exemplo, a propriedade `cursor: pointer` nos _buttons_ e qualquer outro local da página que seja clicável. Seria interessante também, começar a criar estilos em arquivos diferentes baseando em modelos de componentes da página, isso vai facilitar futuras manutenções do código e reutilização caso o projeto venha a crescer muito. Por fim, pode buscar novas ideias e exemplos de implementações acessando _sites_ conhecidos e inspecionando o código através do _browser_ .

**Comment by raquel-maia** [comment]
Obrigada pelas dicas Re! Segui sua dica e adicionei a propriedade cursor:pointer. Além disso, também coloquei links nas imagens e botões de tamanho para direcionar para o site de vendas. Aproveitem para refatorar o  código por completo e remover alguns duplicados.
Em breve vou criar variáveis para facilitar futuras manutenções do código e buscar novas ideias.

**Comment by Re04nan** [comment]
Muito bom, continue a compartilhar cada evolução do site, tenho certeza que se continuar se dedicando ele vai evoluir muito.
